print(" ") #Espacio
print("REYES MEZA ALAN EDUARDO 1207 : 3W") #Datos del programador
print(" ") #Espacio

# Lista con nombre y dos apellidos
nombre_apellidos = ["Alan", "Reyes", "Meza"]

# Imprimir los apellidos usando índices
primer_apellido = nombre_apellidos[1]  # El primer apellido está en el índice 1
segundo_apellido = nombre_apellidos[2]  # El segundo apellido está en el índice 2

print("Primer apellido:", primer_apellido)
print("Segundo apellido:", segundo_apellido)
