print(" ") #Espacio
print("REYES MEZA ALAN EDUARDO 1207 : 3W") #Datos del programador
print(" ") #Espacio

# Definir el nombre y apellido
nombre = input("Introduce el nombre: ")
apellido = input("Introduce el apellido: ")

# Comprobar el nombre y el apellido
if nombre == "Daniel":
    if apellido == "Ramos":
        print("Nombre y apellido correctos")
    else:
        print("Apellido incorrecto")
else:
    print("Usuario desconocido")
